### ISSUE TITLE
Setup GitHub Actions/Pipelines for automatic CI

### ISSUE THREAD

**Issue by oruebel** [hdmf-dev/hdmf-zarr#10]
Similar to the main HDMF we should run the following all pull requests
- flake8 (or black)
- unit tests
- gallery tests for sphinx gallery as part of the docs
- docs build
- linkcheck on docs
- May Require #18 (but not sure)

For this we can most likely build off the workflows defined in HDMF https://github.com/hdmf-dev/hdmf/tree/dev/.github/workflows

**Comment by bendichter** [comment]
+1 for black. See how we set it up here:

https://github.com/NeurodataWithoutBorders/nwbinspector/blob/803756995f84d04bf543c85fb1684961e6290643/.pre-commit-config.yaml

https://github.com/NeurodataWithoutBorders/nwbinspector/blob/60e081c68710308c05a48f6b2211480b38e98589/pyproject.toml

https://github.com/NeurodataWithoutBorders/nwbinspector/blob/bac7056cc5f2c61a1444b5a6c8a9e990a5c26b4c/.github/workflows/black.yml

**Comment by oruebel** [comment]
> +1 for black

👍 I have not used black before, but I won't stand in the way of progress 😉

**Comment by oruebel** [comment]
Fixed in #32
