### ISSUE TITLE
[Feature]: Run tests again dev branch of HDMF

### ISSUE THREAD

**Issue by oruebel** [hdmf-dev/hdmf-zarr#126]
### What would you like to see added to HDMF-ZARR?

To detect errors due to changes in the dev branch of HDMF it will be useful to run tests against the lastest HDMF on the dev branch. These tests should not be required for merge.

### Is your feature request related to a problem?

The test suite currently fails when running against HMDF on the dev branch

### What solution would you like?

...

### Do you have any interest in helping implement the feature?

No.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/hdmf-dev/hdmf-zarr/blob/dev/.github/CODE_OF_CONDUCT.md)
- [X] Have you checked the [Contributing](https://github.com/hdmf-dev/hdmf-zarr/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/hdmf-dev/hdmf-zarr/issues)?

**Comment by mavaylon1** [comment]
You want to have a workflow here that runs HDMF-Zarr but using the dev branch of HDMF rather than the released HDMF correct? @oruebel

**Comment by oruebel** [comment]
Correct

**Comment by mavaylon1** [comment]
> Correct

Will do
