### ISSUE TITLE
[Feature]: Create an example NWB Zarr dataset 

### ISSUE THREAD

**Issue by rly** [hdmf-dev/hdmf-zarr#135]
### What would you like to see added to HDMF-ZARR?

It would be nice to have a test NWB (or HDMF) Zarr dataset stored somewhere like our Google Drive, that users can download to explore its structure without having to run code.

### What solution would you like?

^

### Do you have any interest in helping implement the feature?

No.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/hdmf-dev/hdmf-zarr/blob/dev/.github/CODE_OF_CONDUCT.md)
- [X] Have you checked the [Contributing](https://github.com/hdmf-dev/hdmf-zarr/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/hdmf-dev/hdmf-zarr/issues)?

**Comment by oruebel** [comment]
We should make a DANDISET for this. I believe Cody already has an older example on DANDI. That is on my docket to look at as part of making streaming from S3 work with HDMF_ZARR as part of #134

**Comment by CodyCBakerPhD** [comment]
There is indeed an example file here: https://gui-staging.dandiarchive.org/dandiset/204919/draft/files?location=test_read_nwbfile&page=1

I believe it's just an ElectricalSeries and associated metadata, but that's something

Still seeking S3 streaming instructions that work with DANDI (the basic Zarr instructions encounter various issues)

**Comment by oruebel** [comment]
> Still seeking S3 streaming instructions that work with DANDI (the basic Zarr instructions encounter various issues)

Sorry, I have not had a chance to work on this yet. I'll try to take a look next week.

**Comment by rly** [comment]
Thanks for sharing the example @CodyCBakerPhD! I forgot that that exists on DANDI staging.

**Comment by mavaylon1** [comment]
@rly can I close this?
