### ISSUE TITLE
[Feature]: Expose `mode` to NWBZarrIO

### ISSUE THREAD

**Issue by CodyCBakerPhD** [hdmf-dev/hdmf-zarr#137]
### What would you like to see added to HDMF-ZARR?

Stems from https://github.com/catalystneuro/neuroconv/pull/569#discussion_r1342411702

The NWBHDF5IO has a `.mode` attribute publicly exposed to easily detect on an instantiated IO object what the mode was at time of instantiation (useful for determining if an in-memory `NWBFile` object was read from an existing file or created on the fly)

But the NWBZarrIO does not; though the same info can be accessed via the private `._ZarrIO__mode` attribute

### Is your feature request related to a problem?

```python
from hdmf_zarr import NWBZarrIO

io = NWBZarrIO(path="../test2.nwb.zarr", mode="r")

io.mode

Traceback (most recent call last):

  Cell In[4], line 1
    io.mode

AttributeError: 'NWBZarrIO' object has no attribute 'mode'
```

### What solution would you like?

Expose `.mode` attribute as public instead of `_ZarrIO__mode`

### Do you have any interest in helping implement the feature?

No.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/hdmf-dev/hdmf-zarr/blob/dev/.github/CODE_OF_CONDUCT.md)
- [X] Have you checked the [Contributing](https://github.com/hdmf-dev/hdmf-zarr/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/hdmf-dev/hdmf-zarr/issues)?

**Comment by oruebel** [comment]
I think `NWBZarrIO.file.mode` should do the trick.

**Comment by CodyCBakerPhD** [comment]
```python
io.file.mode
Traceback (most recent call last):

  File ~\AppData\Roaming\Python\Python310\site-packages\zarr\hierarchy.py:520 in __getattr__
    return self.__getitem__(item)

  File ~\AppData\Roaming\Python\Python310\site-packages\zarr\hierarchy.py:500 in __getitem__
    raise KeyError(item)

KeyError: 'mode'
```

Also, more to the original issue as requested by @bendichter, he wanted a universal API consistency with NWBHDF5IO in this respect

**Comment by oruebel** [comment]
If I remember correctly not all stores in Zarr actually support `mode`. The standard `NestedDirectoryStore`, e.g., I believe does not have a `mode`

**Comment by oruebel** [comment]
Looking at https://zarr.readthedocs.io/en/stable/api/storage.html#zarr.storage.DirectoryStore (which is what Zarr uses by default), does not have a `mode`. The convenience functions `zarr.convenience.open` and other have a `mode` but I'm not sure right now where that is being stored (maybe, `NWBZarrIO.file.store.mode`)

**Comment by oruebel** [comment]
Since the Zarr DirectoryStore does not use a mode (which is the main store used in HDFM Zarr), we decided to close this issue. If a use case for this arises please reopen the issue.

**Comment by oruebel** [comment]
We can expose the `mode` used when calling `ZarrIO`, but that may not match exactly the mode that Zarr actually uses. E.g., we may use `r` when calling `ZarrIO` but the `DirectoryStore` in Zarr will still treat is as append. However, exposing the parameter that the user set on __init__ seems still reasonable.
