### ISSUE TITLE
Remove strict dependency for numcodecs to support python 3.12

### ISSUE THREAD

**Issue by h-mayorquin** [hdmf-dev/hdmf-zarr#162]
We are failing to support python 3.12 in neuroconv because hdmf-zarr has the following hard pin on numcodecs:

https://github.com/hdmf-dev/hdmf-zarr/blob/300070ba8be3ebf5525defcd4a3f3339a36b3272/pyproject.toml#L34-L35

(it also seems to be repeated)

Could we make this a soft dependency on the version? 

numcodecs 0.12 introduced python 3.12 support:
https://numcodecs.readthedocs.io/en/stable/release.html

I can push a PR to change this but I just wanted to discuss this before.

**Comment by oruebel** [comment]
> it also seems to be repeated

Thanks for the catch, that look like a bug

> Could we make this a soft dependency on the version

Having a soft dependency should be fine. I'm not sure what the lowest version is that we should allow for numcodecs, but I think >=0.11.0 should be fine.

**Comment by oruebel** [comment]
Looking at the minimum requirements, we are testing with  'numcodecs==0.9.1', so I'll make that the minimum.

https://github.com/hdmf-dev/hdmf-zarr/blob/f180b443afe87478b2a3eb04eb2d9bf17bbb0978/requirements-min.txt#L3
