### ISSUE TITLE
[Feature]: support Python 3.12

### ISSUE THREAD

**Issue by bendichter** [hdmf-dev/hdmf-zarr#166]
### What would you like to see added to HDMF-ZARR?

We are trying to enhance NeuroConv to support Python 3.12 (https://github.com/catalystneuro/neuroconv/pull/626), however we are having trouble due to the numcodecs dependency. Since numcodecs is a dependency of this package, and this package does not yet test for Python 3.12 compatibility, so I think it makes sense to work on support for Python 3.12 first.

### What solution would you like?

The first step would involve changing the workflows to move the Python version upper bound from 3.11 to 3.12. Then we can see what is failing and go from there.

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/hdmf-dev/hdmf-zarr/blob/dev/.github/CODE_OF_CONDUCT.md)
- [X] Have you checked the [Contributing](https://github.com/hdmf-dev/hdmf-zarr/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/hdmf-dev/hdmf-zarr/issues)?

**Comment by h-mayorquin** [comment]
Related:
https://github.com/hdmf-dev/hdmf-zarr/issues/162

**Comment by oruebel** [comment]
> however we are having trouble due to the numcodecs dependency.

The issue with the numcodecs version should be resolved by https://github.com/hdmf-dev/hdmf-zarr/pull/163 , which is part of the latest `0.6.0` release. Hopefully that helps you move forward on the NeuroConv side.

> The first step would involve changing the workflows to move the Python version upper bound from 3.11 to 3.12. Then we can see what is failing and go from there

@mavaylon1 can you take a stab at this

**Comment by CodyCBakerPhD** [comment]
NeuroConv is all good now: https://github.com/catalystneuro/neuroconv/pull/626

Still a good idea for y'all to extend your CI though

**Comment by mavaylon1** [comment]
Will do.
