### ISSUE TITLE
[Feature]: Refactor tox.ini to match HDMF

### ISSUE THREAD

**Issue by mavaylon1** [hdmf-dev/hdmf-zarr#169]
### What would you like to see added to HDMF-ZARR?

A few months ago, HDMF "simplified" tox.ini. After updating for 3.12 support, we should refactor to a similar form.

### What solution would you like?

Above.

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/hdmf-dev/hdmf-zarr/blob/dev/.github/CODE_OF_CONDUCT.md)
- [X] Have you checked the [Contributing](https://github.com/hdmf-dev/hdmf-zarr/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/hdmf-dev/hdmf-zarr/issues)?

**Comment by rly** [comment]
As @mavaylon1 and I discussed, the current verbose `tox.ini` form in hdmf-zarr is fine, so this refactor is not necessary.
