### ISSUE TITLE
[Documentation]: `linkable` key has been deprecated

### ISSUE THREAD

**Issue by oruebel** [hdmf-dev/hdmf-zarr#177]
### What would you like changed or added to the documentation and why?

https://github.com/hdmf-dev/hdmf-schema-language/pull/27 deprecated the `linkable` key. `hdmf-zarr` does not support this key right now either. I would suggest removing it from the docs (and also check if it appears anywhere in the code)

https://github.com/hdmf-dev/hdmf-zarr/blob/6e946dabc2370bb428787fbe7d1ec919ba1fd11f/docs/source/storage.rst?plain=1#L92

https://github.com/hdmf-dev/hdmf-zarr/blob/6e946dabc2370bb428787fbe7d1ec919ba1fd11f/docs/source/storage.rst?plain=1#L58

### Do you have any interest in helping write or edit the documentation?

No.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/hdmf-dev/hdmf-zarr/blob/dev/.github/CODE_OF_CONDUCT.md)
- [X] Have you checked the [Contributing](https://github.com/hdmf-dev/hdmf-zarr/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/hdmf-dev/hdmf-zarr/issues)?

**Comment by oruebel** [comment]
I think this is probably just a simple 2-line update in the docs.

**Comment by mavaylon1** [comment]
Can do
