### ISSUE TITLE
[Feature]: NWBZarrIO should have load_namespaces=True by default

### ISSUE THREAD

**Issue by rly** [hdmf-dev/hdmf-zarr#198]
### What would you like to see added to HDMF-ZARR?

Following this change in PyNWB https://github.com/NeurodataWithoutBorders/pynwb/pull/1748

### What solution would you like?

Consistency between NWBHDF5IO and NWBZarrIO

### Do you have any interest in helping implement the feature?

No.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/hdmf-dev/hdmf-zarr/blob/dev/.github/CODE_OF_CONDUCT.md)
- [X] Have you checked the [Contributing](https://github.com/hdmf-dev/hdmf-zarr/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/hdmf-dev/hdmf-zarr/issues)?

**Comment by mavaylon1** [comment]
I'll take a look next week.

**Comment by mavaylon1** [comment]
Context: We want to have load_namespaces to be True by default. This reads cached schemas and automatically tries to generate the API for any missing namespaces. The prime example being extensions.


On the pynwb side, I do not see any tests involving a roundtrip for a file with extensions, testing the whole load_namespace finding the cached schemas.
