### ISSUE TITLE
Add support for storing region references

### ISSUE THREAD

**Issue by oruebel** [hdmf-dev/hdmf-zarr#47]
Region references are not yet fully implemented in `ZarrIO`. To implement region references will require updating:
  1)  `ZarrReference` to add a ``region`` key to support storing the selection for the region,
  2) `ZarrIO.__get_ref` to support passing in the region definition to be added to the`ZarrReference`
  3) `ZarrIO.write_dataset` already partially implements the required  logic for creating region references by checking for  hdmf.build.RegionBuilder` inputs but will likely need updates as well
  4) `ZarrIO.__read_dataset` to support reading region references, which may also require updates to `ZarrIO.__parse_ref` and
  `ZarrIO.__resolve_ref`, 
  5) and possibly other parts of `ZarrIO`

**Comment by rly** [comment]
What is the use case for region references? As far as I know, they are not used by NWB or any other application of HDMF. I wonder if this legacy functionality can be removed from HDMF for simplicity of the framework and other backends.

**Comment by oruebel** [comment]
> What is the use case for region references?

I created the issues only to make sure that we have issues in GitHub to track known limitations of the Zarr backend in terms of features that HDMF has but which are not yet supported in hdmf-zarr. I didn't have a specific use case in mind here. 

> As far as I know, they are not used by NWB or any other application of HDMF. I wonder if this legacy functionality can be removed from HDMF for simplicity of the framework and other backends.

I believe that is correct; as far as I know NWB, HDMF-Common, and to the best of my knowledge non of the NDX extensions use region references. This is in large part, because the main place we need references to regions is for data tables, and for that we have DynamicTableRegion because region references don't work in that case because they can only reference a single dataset and we wanted to make it easy to inspect the indices (i.e., rows) that are being references. In principle, removing support for region references in HDMF to simplify code and reduce technical dept I think could be a reasonable option.

**Comment by rly** [comment]
Region references are being deprecated from HDMF, so this is no longer necessary.
