### ISSUE TITLE
Update tox.ini to use test_gallery.py and fix gallery-python-3.7 tests

### ISSUE THREAD

**Issue by mavaylon1** [hdmf-dev/hdmf-zarr#52]
1. Update tox.ini to use test_gallery.py to be in line with HDMF
2. Currently both linux-gallery-python3.7-minimum and windows-gallery-python3.7-minimum will pass locally when running "python test.py --example", but not during the github checks. I've also tested a version of test_gallery.py by running in a branch "python test_gallery.py"; however, this returns an error regarding missing files. (Refer to attached images)
![Screen Shot 2022-12-21 at 11 01 36 AM](https://user-images.githubusercontent.com/22578631/209206869-e13107b7-5138-486b-8cc7-e7c3fe7af017.png)

**Comment by mavaylon1** [comment]
@rly I'd love some help with this. I've tested all my ideas of checking if the the files are indeed found in the directory by printing out the list of files used in test_gallery.py, and fiddling with absolute paths.

**Comment by rly** [comment]
I'll take a look

**Comment by rly** [comment]
Closed with #52
