### ISSUE TITLE
Set up readthedocs auto-build on PR

### ISSUE THREAD

**Issue by rly** [hdmf-dev/hdmf-zarr#69]
On each PR on the HDMF repo, readthedocs will build the documentation which we can then review. @mavaylon1 could you please set this up on this repo?

**Comment by mavaylon1** [comment]
@rly could you elaborate?

**Comment by CodyCBakerPhD** [comment]
Someone with admin permissions on the ReadtheDocs goes to the 'integrations' tab and sets up a 'webhook', if my memory serves

It can be a little touchy though, I've had to delete/restart it a couple times when first setting it up
