### ISSUE TITLE
Pipelines failing due to codecov

### ISSUE THREAD

**Issue by oruebel** [hdmf-dev/hdmf-zarr#73]
CI pipelines are failing with:

```
ERROR: Could not find a version that satisfies the requirement codecov==2.1.12 (from versions: 2.1.13)
```

**Comment by oruebel** [comment]
@rly @mavaylon1 is this something you can help with? I believe you fixed this in HDMF and PyNWB already.

**Comment by rly** [comment]
The solution is to remove it as a dependency. Codecov is used only for uploading code coverage reports, and they recommend using their GitHub Action and/or non-python uploader script now. See https://github.com/hdmf-dev/hdmf/pull/849
