### ISSUE TITLE
conda-linux-python3.7-minimum test failing

### ISSUE THREAD

**Issue by rly** [hdmf-dev/hdmf-zarr#76]
```
py37-minimum create: /home/runner/work/hdmf-zarr/hdmf-zarr/.tox/py37-minimum
ERROR: invocation failed (exit code 1), logfile: /home/runner/work/hdmf-zarr/hdmf-zarr/.tox/py37-minimum/log/py37-minimum-0.log
================================== log start ===================================
AttributeError: 'dict' object has no attribute 'select'

=================================== log end ====================================
ERROR: InvocationError for command /usr/share/miniconda/envs/true/bin/python3.7 -m virtualenv --download --python /usr/share/miniconda/envs/true/bin/python3.7 py37-minimum (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   py37-minimum: InvocationError for command /usr/share/miniconda/envs/true/bin/python3.7 -m virtualenv --download --python /usr/share/miniconda/envs/true/bin/python3.7 py37-minimum (exited with code 1)
```

**Comment by rly** [comment]
Same issue as in https://github.com/hdmf-dev/hdmf/pull/823

**Comment by bendichter** [comment]
I would like to propose we adopt this policy: https://numpy.org/neps/nep-0029-deprecation_policy.html

and drop 3.7

**Comment by rly** [comment]
@bendichter I think that is a fine policy for the popular packages that were relatively stable four years ago. However, I worry that our users who must use an older version of Python because of other requirements (e.g., allensdk is often slow to update python support, tensorflow versions are often linked to hardware) will lose access to the bug fixes that we make in the latest version. So unless we have a strong need to drop a Python version (we need the new features, or maintenance is just a real pain), I would like to err on the more conservative side for our core packages (pynwb, hdmf, hdmf-zarr) and for those, support Python versions up until the official Python end of life dates https://endoflife.date/python . The difference is an additional 18 months of support (42 months in the numpy policy vs 60 in the python policy) for the oldest versions of Python.
