### ISSUE TITLE
HDMF Zarr needs to be compatible with HDMF 3.5.5 and up

### ISSUE THREAD

**Issue by mavaylon1** [hdmf-dev/hdmf-zarr#79]
Currently, hdmf-zarr is only compatible with >=3.5.2 and <=3.5.4
We need to fix the issues on why 3.5.5 won't work

**Comment by oruebel** [comment]
This is likely related to fixes of export in 3.5.5. It's unclear whether the error is in HDMF or whether the fixes in HDMF reveal a previously "hidden" issue in hdmf-zarr. Relevant HDMF PRs are likely:
https://github.com/hdmf-dev/hdmf/pull/847
https://github.com/hdmf-dev/hdmf/pull/848

**Comment by rly** [comment]
@mavaylon1 any update on this?

**Comment by mavaylon1** [comment]
> @mavaylon1 any update on this?

The last time I believe we hit a wall trying to find the problem during the paired programming. I'll take a look after the other issues are solved/merged regarding mock/links.

**Comment by mavaylon1** [comment]
This might be another project for me to work on later this week but also throughout the dev days. @rly
I'll see if I recorded that mentioned pair programming session to see where we left off.
