### ISSUE TITLE
[Documentation]: Add installation instructions

### ISSUE THREAD

**Issue by bendichter** [hdmf-dev/hdmf-zarr#94]
### What would you like changed or added to the documentation and why?

https://hdmf-zarr.readthedocs.io/en/latest/installation.html

The "latest" still appears as:
<img width="453" alt="image" src="https://github.com/hdmf-dev/hdmf-zarr/assets/844306/c239c6fd-1194-457a-9446-e6d7d2c59d7a">

### Do you have any interest in helping write or edit the documentation?

No.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/hdmf-dev/hdmf-zarr/blob/dev/.github/CODE_OF_CONDUCT.md)
- [X] Have you checked the [Contributing](https://github.com/hdmf-dev/hdmf-zarr/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/hdmf-dev/hdmf-zarr/issues)?

**Comment by oruebel** [comment]
Looks like this may be an issue with readthedocs not updating correctly. On the dev branch the docs have been updated:

https://github.com/hdmf-dev/hdmf-zarr/blob/dev/docs/source/installation.rst

**Comment by oruebel** [comment]
@mavaylon1 I believe this issue should be fixed once you make the release.
